const MarkovGen = require('markov-generator');

let markov = new MarkovGen({
  input: [
    'Just in case there was anyone still out there mistaking me for some sort of domestic diva, or even a moderately skilled at being domestic, you should know that it has taken until the spring of the year 2016, nearly a full decade after starting a food website where I’ve had the brass to coax others along in the kitchen as if I had some sort of innate greater understanding of it, for me to learn how to use my broiler. Prior to consulting experts reading my oven’s manual um, Googling it a few months ago, I couldn’t for the life of me figure out why other people managed to broil things whenever they needed for as long as they needed but mine shut off after 4 minutes. It turns out that cracking open the oven door keeps the temperature from getting so high in the oven that it goes into a panic a shuts off, freeing me fulfill my lifelong fantasy of setting all my food on fire. ',
    'I’m only a little bit joking. Last summer, trying to return to a level of normalcy in the weeks after bringing the sweetest potato home from the hospital, Alex and I spent a week Netflix binging on the first season of Chef’s Table and I fell head over heels for cooking I will probably never experience in my life, that from Francis Mallmann. Mallmann is an Argentine chef whose specialty is wild, open-fire cooking — everything over wood fire, usually in an open pit, on cast iron planchas and parrillas, and sometimes in the ashes too. And his food looks out of this world — even something as simple as a cheese toast made with a log of goat cheese you can get at your local Stop & Shop is transformed in a griddle over open flames into a crisp, golden-brown crusted melt that I would climb through a television screen to get at. The episode ended and I declared it time to get a fire pit. My husband cited fire codes and other pesky side effects of living in the Lower East Side of Manhattan. I sulked.',
    'But now that I have a functioning broiler — or, to be clear, now I am functioning at using my broiler — and at least the tiniest portion of this desire to cook and eat artfully charred food is sated. I am also now able, at last, to return to some of the simplest delights of high-heat cooking, in this case, broiled citrus. We’re at the tail end of peak citrus right now as (hopefully) we’re going to be reacquainted with fresh, local spring produce soon, and I wanted to have one last hurrah with the Moros, the Cara Caras and Minneolas before they’re gone. Broiling them with a thin schmear of light brown sugar transforms them into something even more special, a fleck of burnt sugar bitterness with the tang of pineapple in the running juices. Chilling them when you’re done creates a distant relative of a compote that you can use for anything you please over the next week — on pancakes, with yogurt and mint for a luxe breakfast or light dessert, or even with a scoop of vanilla ice cream for an unexpected treat, and I didn’t have to break any laws to pull it off.',
    'Let this be my contribution to the “no recipes” movement, because you are not going to need one here. What you need is some brown sugar, a few oranges, even imperfect ones, some yogurt and a few leaves of mint. You do not need measuring spoons. You will be most successful if you keep an eye on it, as broilers will vary in how fast they get things done. But, here’s roughly how to do it:',
    'Look, no one is ever going to marry me for my pavlova. (I mean, talking about dodging a bullet…) This one was particularly underachieving. First, I thought I’d be clever and try to add the cocoa at the start, mixed with the sugar, so that it would mix the best. Nope! It never fully whipped. With this in the trash, I began my next one, breaking an egg yolk right into the white. I can usually get it all out (tip! use the empty shell as a scooper/skimmer) but not this time. I started a new bowl and, yup, did it again. Finally, with six uncompromised egg whites and cocoa stirred in only at the very end, ensuring a respectably thick, shiny plume of meringue, I began piling my chocolate plumes on a 9-inch round parchment circle, only to realize this wasn’t very bright, as the meringue would spread. I cut a new, larger square of parchment and used the old one as a sling/tube-of-a-pastry bag to land the new one in a great, elegant swirl and then fell over laughing (and texting everyone I know with the picture because: all grownup here!) because it looked precisely like everyone’s favorite emoji. Smoothed into more of a mound, I baked it at the wrong temperature and it got too crispy and riddled with cracks. Anyone left reading from New Zealand just is doing this right now.  (Don’t worry, I retested it — woe is me — to confirm that the correct temperature and times are indeed correct.)',
    'But I have one thing going for us, and that’s that this pavlova is the most chocolaty I’ve ever had. The apartment air was steeped with eau de brownies, the very best perfume. Even a day later, this cake of a meringue is decadent but not heavy, basically dessert magic. Do not be deceived, as I have been in the past, by the pale beige shade of the outer shell — inside, it’s like a truffle with the impact of and the texture of a pillow. ',
    'One of the reasons I think pavlovas can be a hard sell outside, say, the Pavlova Motherlands of Australia and New Zealand, is that I hear from most people that they find them to be too sweet. But I was able to reduce the sugar a bit from the norm here and didn’t miss it; adding salt also helps as does chocolate, not just because things with chocolate > things without chocolate but because the bitterness of cocoa and chopped chocolate here really kept the sugar in check, as does a plume of barely sweetened whipped cream and a cascade of berries. Let’s not even pretend that we don’t want to swan dive in.',
    'Given my fixation with both walnuts and everyday cakes, it should come as exactly no surprise that the time between me spying this recipe and me getting it in the oven was about six days. Which is the equivalent of less than one day in If You Don’t Have An Impish Four-Month Old terms. I fell for it quickly, it came together even faster (spoiler: the whole thing can be made in a single-bowl food processor) and all of that voluptuous stuff on top — a schmear of jam and a “drift” of whipped cream that’s been tarted up with a little sour cream — are standard no-fuss ingredients. This cake is an easy win.',
    'And yet, I must fuss. It is my way. I am 33 years old, clearly too old and entrenched to change. I found the jam a little overpowering. Now, I intentionally went out and sought a jam that would be more tart than sweet, and then I did add the optional lemon juice to further the punch. Nonetheless, when you have a subtly delightful cake — built on a flavor bed of walnuts toasted nearly to the point of caramelization) — it’s hard to find that under a pile of jam. I might halve it next time, or just spread a thin slick of it on top.  Or even skip it and for once, listen to my husband who thinks that everything is better with chocolate and perhaps puddle some ganache on top instead. Or my waistline, that thinks this cake is rich enough plain? Nah, definitely the husband.',
    'And the whipped-with-a-touch-of-sour cream, lordy, I was excited about that but wow, that sure is a lot of it.  I barely even know who is talking right now, because surely this would never come out of my own mouth but maybe a little less whipped cream next time? Clearly, I’m feeling under the weather today and it shows.',
    'Beyond my fussing, however, this is one of those cakes that I can imagine as many, many things: I could see it as a birthday layer cake. Or the kind of breakfast muffins you know are really just small cakes but look, jam! Clearly that makes them breakfast material. You could split the cake once or twice and slip the jam between the layers, if you’re feeling fancy. Pecans would be an obvious substitution, if you don’t like walnuts (but how could you not?). And I dare say that given the small amount of flour in the cake, it seems ripe for some Kosher for Passover or Gluten-Free adaptability, yes?'
  ],
  minLength: 10
});

let sentence = markov.makeChain();
console.log(sentence);